- type: job
  id: CEBard
  setPreference: true
  name: ce-job-name-bard
  description: ce-job-desc-bard
  playTimeTracker: CEJobBard
  startingGear: CEBardGear
  icon: CEJobIconBard
  supervisors: ce-job-supervisors-empire
  canBeAntag: true

- type: startingGear
  id: CEBardGear
  equipment:
    pocket1: CEWalletFilledBard

- type: entity
  id: CEWalletFilledBard
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #50cp total
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10
    - id: CECoinCopper10
